// <auto-generated />
using System;
using CS4540_A2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CS4540A2.Migrations
{
    [DbContext(typeof(LOSContext))]
    [Migration("20190925211347_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CS4540_A2.Models.Course", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dept")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<string>("Description");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Number");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<int>("Year");

                    b.HasKey("CId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CId = 1,
                            Dept = "CS",
                            Description = "Software architectures, programming models, and programming environments pertinent to developing web applications.  Topics include client-server model, multi-tier software architecture, client-side scripting (JavaScript), server-side programming (Servlets and JavaServer Pages), component reuse (JavaBeans), database connectivity (JDBC), and web servers.",
                            Email = "professor_jim@cs.utah.edu",
                            Name = "Web Development",
                            Number = 4540,
                            Semester = "FA",
                            Year = 2019
                        },
                        new
                        {
                            CId = 2,
                            Dept = "CS",
                            Description = "This course provides an introduction to the problem of engineering computational efficiency into programs.Students will learn about classical algorithms(including sorting, searching, and graph traversal),data structures(including stacks, queues, linked lists, trees, hash tables, and graphs),and analysis of program space and time requirements.Students will complete extensive programming exercises that require the application of elementary techniques from software engineering.",
                            Email = "professor_jim@cs.utah.edu",
                            Name = "Algorithms",
                            Number = 2420,
                            Semester = "FA",
                            Year = 2019
                        },
                        new
                        {
                            CId = 3,
                            Dept = "CS",
                            Description = "Practical exposure to the process of creating large software systems, including requirements specifications, design, implementation, testing, and maintenance. Emphasis on software process, software tools (debuggers, profilers, source code repositories, test harnesses), software engineering techniques (time management, code, and documentation standards, source code management, object-oriented analysis and design), and team development practice. Much of the work will be in groups and will involve modifying preexisting software systems.",
                            Email = "professor_jim@cs.utah.edu",
                            Name = "Software Practice I",
                            Number = 3500,
                            Semester = "FA",
                            Year = 2019
                        },
                        new
                        {
                            CId = 4,
                            Dept = "CS",
                            Description = "Introduction to propositional logic, predicate logic, formal logical arguments, finite sets, functions, relations, inductive proofs, recurrence relations, graphs, probability, and their applications to Computer Science.",
                            Email = "professor_mary@cs.utah.edu",
                            Name = "Discrete Structures",
                            Number = 2100,
                            Semester = "FA",
                            Year = 2019
                        },
                        new
                        {
                            CId = 5,
                            Dept = "CS",
                            Description = "Introduction to computer systems from a programmer's point of view.  Machine level representations of programs, optimizing program performance, memory hierarchy, linking, exceptional control flow, measuring program performance, virtual memory, concurrent programming with threads, network programming.",
                            Email = "professor_mary@cs.utah.edu",
                            Name = "Computer Systems",
                            Number = 4400,
                            Semester = "FA",
                            Year = 2019
                        },
                        new
                        {
                            CId = 6,
                            Dept = "CS",
                            Description = "Practical exposure to the process of creating large software systems, including requirements specifications, design, implementation, testing, and maintenance. Emphasis on software process, software tools (debuggers, profilers, source code repositories, test harnesses), software engineering techniques (time management, code, and documentation standards, source code management, object-oriented analysis and design), and team development practice. Much of the work will be in groups and will involve modifying preexisting software systems.",
                            Email = "professor_danny@cs.utah.edu",
                            Name = "Software Practice I",
                            Number = 3500,
                            Semester = "FA",
                            Year = 2019
                        });
                });

            modelBuilder.Entity("CS4540_A2.Models.LearningOutcome", b =>
                {
                    b.Property<int>("LId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseCId");

                    b.Property<int?>("CourseId");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("LId");

                    b.HasIndex("CourseId");

                    b.ToTable("LOS");

                    b.HasData(
                        new
                        {
                            LId = 1,
                            CourseCId = 1,
                            Description = "Construct web pages using modern HTML and CSS practices, including modern frameworks",
                            Name = "HTML CSS"
                        },
                        new
                        {
                            LId = 2,
                            CourseCId = 1,
                            Description = "Define accessibility and utilize techniques to create accessible web pages",
                            Name = "Create accessible web pages"
                        },
                        new
                        {
                            LId = 3,
                            CourseCId = 1,
                            Description = "Outline and utilize MVC technologies across the “full-stack” of web design (including front-end, back-end, and databases) to create interesting web applications. Deploy an application to a “Cloud” provider.",
                            Name = "MVC"
                        },
                        new
                        {
                            LId = 4,
                            CourseCId = 1,
                            Description = "Describe the browser security model and HTTP; utilize techniques for data validation, secure session communication, cookies, single sign-on, and separate roles.  ",
                            Name = "Security model"
                        },
                        new
                        {
                            LId = 5,
                            CourseCId = 1,
                            Description = "Utilize JavaScript for simple page manipulations and AJAX for more complex/complete “single-page” application.",
                            Name = "JavaScript "
                        },
                        new
                        {
                            LId = 6,
                            CourseCId = 1,
                            Description = "Demonstrate how responsive techniques can be used to construct applications that are usable at a variety of page sizes.  Define and discuss responsive, reactive, and adaptive.",
                            Name = "Responsive pages"
                        },
                        new
                        {
                            LId = 7,
                            CourseCId = 1,
                            Description = "Construct a simple web-crawler for validation of page functionality and data scraping.",
                            Name = "web-crawler"
                        },
                        new
                        {
                            LId = 8,
                            CourseCId = 5,
                            Description = "Explain the objectives and functions of abstraction layers in modern computing systems, including operating systems, programming languages, compilers, and applications",
                            Name = "Modern computing systems"
                        },
                        new
                        {
                            LId = 9,
                            CourseCId = 5,
                            Description = "Understand cross-layer communications and how each layer of abstraction is implemented in the next layer of abstraction (such as how C programs are translated into assembly code and how C library allocators are implemented in terms of operating system memory management)",
                            Name = "Cross-layer communications"
                        },
                        new
                        {
                            LId = 10,
                            CourseCId = 5,
                            Description = "Analyze how the performance characteristics of one layer of abstraction affect the layers above it (such as how caching and services of the operating system affect the performance of C programs)",
                            Name = "Performance"
                        },
                        new
                        {
                            LId = 11,
                            CourseCId = 5,
                            Description = "Construct applications using operating-system concepts (such as processes, threads, signals, virtual memory, I/O)",
                            Name = "Memory Management"
                        },
                        new
                        {
                            LId = 12,
                            CourseCId = 5,
                            Description = "Synthesize operating-system and networking facilities to build concurrent, communicating applications",
                            Name = "Multi-threading"
                        },
                        new
                        {
                            LId = 13,
                            CourseCId = 5,
                            Description = "Implement reliable concurrent and parallel programs using appropriate synchronization constructs",
                            Name = "Parallel"
                        },
                        new
                        {
                            LId = 14,
                            CourseCId = 3,
                            Description = "Design and implement large and complex software systems (including concurrent software) through the use of process models (such as waterfall and agile), libraries (both standard and custom), and modern software development tools (such as debuggers, profilers, and revision control systems)",
                            Name = "Software systems"
                        },
                        new
                        {
                            LId = 15,
                            CourseCId = 3,
                            Description = "Perform input validation and error handling, as well as employ advanced testing principles and tools to systematically evaluate software",
                            Name = "Validation,testing"
                        },
                        new
                        {
                            LId = 16,
                            CourseCId = 3,
                            Description = "Apply the model-view-controller pattern and event handling fundamentals to create a graphical user interface",
                            Name = "MVC"
                        },
                        new
                        {
                            LId = 17,
                            CourseCId = 3,
                            Description = "Exercise the client-server model and high-level networking APIs to build a web-based software system",
                            Name = "Services"
                        },
                        new
                        {
                            LId = 18,
                            CourseCId = 3,
                            Description = "Operate a modern relational database to define relations, as well as store and retrieve data",
                            Name = "Database"
                        },
                        new
                        {
                            LId = 19,
                            CourseCId = 3,
                            Description = "Appreciate the collaborative nature of software development by discussing the benefits of peer code reviews",
                            Name = "Peer Review"
                        },
                        new
                        {
                            LId = 20,
                            CourseCId = 6,
                            Description = "Design and implement large and complex software systems (including concurrent software) through the use of process models (such as waterfall and agile), libraries (both standard and custom), and modern software development tools (such as debuggers, profilers, and revision control systems)",
                            Name = "Software systems"
                        },
                        new
                        {
                            LId = 21,
                            CourseCId = 6,
                            Description = "Perform input validation and error handling, as well as employ advanced testing principles and tools to systematically evaluate software",
                            Name = "Validation,testing"
                        },
                        new
                        {
                            LId = 22,
                            CourseCId = 6,
                            Description = "Apply the model-view-controller pattern and event handling fundamentals to create a graphical user interface",
                            Name = "MVC"
                        },
                        new
                        {
                            LId = 23,
                            CourseCId = 6,
                            Description = "Exercise the client-server model and high-level networking APIs to build a web-based software system",
                            Name = "Services"
                        },
                        new
                        {
                            LId = 24,
                            CourseCId = 6,
                            Description = "Operate a modern relational database to define relations, as well as store and retrieve data",
                            Name = "Database"
                        },
                        new
                        {
                            LId = 25,
                            CourseCId = 6,
                            Description = "Appreciate the collaborative nature of software development by discussing the benefits of peer code reviews",
                            Name = "Peer Review"
                        },
                        new
                        {
                            LId = 26,
                            CourseCId = 2,
                            Description = "Implement, and analyze for efficiency, fundamental data structures (including lists, graphs, and trees) and algorithms (including searching, sorting, and hashing)",
                            Name = "Data Structures"
                        },
                        new
                        {
                            LId = 27,
                            CourseCId = 2,
                            Description = "Employ Big-O notation to describe and compare the asymptotic complexity of algorithms, as well as perform empirical studies to validate hypotheses about running time",
                            Name = "Time Complexity"
                        },
                        new
                        {
                            LId = 28,
                            CourseCId = 2,
                            Description = "Recognize and describe common applications of abstract data types (including stacks, queues, priority queues, sets, and maps)",
                            Name = "Abstract Data Types"
                        },
                        new
                        {
                            LId = 29,
                            CourseCId = 2,
                            Description = "Apply algorithmic solutions to real-world data",
                            Name = "Algorithm"
                        },
                        new
                        {
                            LId = 30,
                            CourseCId = 2,
                            Description = "Use generics to abstract over functions that differ only in their types",
                            Name = "Generics"
                        },
                        new
                        {
                            LId = 31,
                            CourseCId = 2,
                            Description = "Appreciate the collaborative nature of computer science by discussing the benefits of pair programming",
                            Name = "Pair Programming"
                        },
                        new
                        {
                            LId = 32,
                            CourseCId = 4,
                            Description = "Use symbolic logic to model real-world situations by converting informal language statements to propositional and predicate logic expressions, as well as apply formal methods to propositions and predicates (such as computing normal forms and calculating validity)",
                            Name = "Predicates"
                        },
                        new
                        {
                            LId = 33,
                            CourseCId = 4,
                            Description = "Analyze problems to determine underlying recurrence relations, as well as solve such relations by rephrasing as closed formulas",
                            Name = "Recurrence relations"
                        },
                        new
                        {
                            LId = 34,
                            CourseCId = 4,
                            Description = "Assign practical examples to the appropriate set, function, or relation model, while employing the associated terminology and operations)",
                            Name = "Sets and models"
                        },
                        new
                        {
                            LId = 35,
                            CourseCId = 4,
                            Description = "Map real-world applications to appropriate counting formalisms, including permutations and combinations of sets, as well as exercise the rules of combinatorics (such as sums, products, and inclusion-exclusion)",
                            Name = "Counting"
                        },
                        new
                        {
                            LId = 36,
                            CourseCId = 4,
                            Description = "Calculate probabilities of independent and dependent events, in addition to expectations of random variables",
                            Name = "Probabilities"
                        },
                        new
                        {
                            LId = 37,
                            CourseCId = 4,
                            Description = "Illustrate by example the basic terminology of graph theory, as wells as properties and special cases (such as Eulerian graphs, spanning trees, isomorphism, and planarity)",
                            Name = "Graph"
                        },
                        new
                        {
                            LId = 38,
                            CourseCId = 4,
                            Description = "Employ formal proof techniques (such as direct proof, proof by contradiction, induction, and the pigeonhole principle) to construct sound arguments about properties of numbers, sets, functions, relations, and graphs",
                            Name = "Proofs"
                        });
                });

            modelBuilder.Entity("CS4540_A2.Models.LearningOutcome", b =>
                {
                    b.HasOne("CS4540_A2.Models.Course", "Course")
                        .WithMany("LOS")
                        .HasForeignKey("CourseId");
                });
#pragma warning restore 612, 618
        }
    }
}
